# need local .env file
master:
#  build: .
  image: bxvip/jenkins:v1.0
  environment:
    JAVA_OPTS: "-Djava.awt.headless=true"
  restart: always
  container_name: jenkins
  ports:
  - "50000:50000"
  - "8085:8080"
  volumes:
  - ./data_jenkins:/var/jenkins_home
  env_file:
  - .env
