version: '3'
services:
  jenkins:
    image: 'jenkins/jenkins:lts'
    container_name: jenkins
    restart: always
    ports:
      - '8085:8085'
      - '50000:50000'
    volumes:
      - '/var/jenkins_home:/var/jenkins_home'
