# mysql 配置

version: '2'
services:
  dbmysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD:
      MYSQL_DATABASE: android
      MYSQL_USER:vic
      MYSQL_PASSWORD: android