# postgres docker-compose.yml 配置
version: '3.1'
services:
  postgres:
    image: postgres:9.6
    restart: always
    container_name: local_postgres
    environment:
      POSTGRES_PASSWORD: android
      POSTGRES_USER: vic
      POSTGRES_DB: table_postger
      PGDATA: /home/vic/postgresql/data
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080